services:
  nessus:
    image: isaudits/nessus
    hostname: nessus
    env_file:
      - config/local.env
    ports:
      - "8834:8834"
    volumes:
      - ./config:/config
      - nessus_data:/opt/nessus/
      
volumes:
  nessus_data:
    name: nessus_data
    # Uncomment below to use local file storage instead of basic named volume
    # Use instead of a bind mount so that container data is copied into data folder on initial launch
    # make sure that./data/nessus exists and is empty or it will not be populated with container data!
    #driver: local
    #driver_opts:
    #  o: bind
    #  type: none
    #  device: ${PWD}/data/nessus